#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_nexus_Darwin="https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-${NEXUS_VERSION}-mac.tgz"
  local url_nexus_Linux="https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-${NEXUS_VERSION}-unix.tar.gz"

  local url_nexus="url_nexus_$(uname -s)"
  local fnm_nexus="$(basename "${!url_nexus}")"
  cache curl "$fnm_nexus" "${!url_nexus}"
  
  mkdir -p "$shome/vendor"
  cd "$shome/vendor"
  case "$fnm_nexus" in
    *.tgz|*.tar.gz)
      tar xvfz "${BASEBOX_CACHE}/curl/$fnm_nexus"
      (cd "$shome/vendor" && mv -f sonatype-work sonatype-work-$(RANDOM)-$$)
      ln -nfs "/data/nexus/sonatype-work" "$shome/vendor/"
      ;;
  esac

  "$shome/script/update"
}

bootstrap
