#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_nexus_Darwin="https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-${NEXUS_VERSION}-mac.tgz"
  local url_nexus_Linux="https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-${NEXUS_VERSION}-unix.tar.gz"

  local url_nexus="url_nexus_$(uname -s)"
  local fnm_nexus="$(basename "${!url_nexus}")"
  cache curl "$fnm_nexus" "${!url_nexus}"
  
  localhost -m file -- state=directory dest="$shome/vendor"
  cd "$shome/vendor"
  case "$fnm_nexus" in
    *.tgz|*.tar.gz)
      tar xfz "${BASEBOX_CACHE}/curl/$fnm_nexus" --exclude sonatype-work
      if [[ ! -d "/data/nexus/sonatype-work" ]]; then
        localhost -m file -- state=directory dest="/data/nexus"
        pushd /data/nexus
        tar xfz "${BASEBOX_CACHE}/curl/$fnm_nexus" sonatype-work
        popd
      fi
      localhost -m file -- state=link src="/data/nexus/sonatype-work" dest="$shome/vendor/sonatype-work"
      ;;
  esac

  localhost -m file -- state=link src="../vendor/nexus-${NEXUS_VERSION}/bin/nexus" dest="$shome/bin/nexus"
}

main "$@"
