#!/usr/bin/env bash

function nexus_profile {
  local shome="${_nexus_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  export PATH="$shome/bin:$PATH"

  export NEXUS_VERSION="3.3.1-01"
}

nexus_profile
