#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  ln -nfs ../vendor/nexus-${NEXUS_VERSION}/bin/nexus "$shome/bin/"
}

bootstrap
