#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_nexus="$(readlink "$shome/bin/nexus" | cut -d/ -f3 | cut -d- -f2- 2>/dev/null || true)"
  jq -n \
    --arg nexus "$ver_nexus" \
    '{nexus: $nexus}'
}

version "$@"
